### ISSUE TITLE
Macro directory opens when you drag a macro to the hotbar

### ISSUE THREAD

**Issue by atleticano-snp** [earlSt1/vtt-macro-folders#18]
Hey! Love your folder module.

I'm having some issues. Everytime that a player (or GM) drag a macro or something, it trigger opening the macro folders. It stop when disactivate the module. It's a potential conflict with some module or it native? In the second case, it is possible to add a 'not open macro folders with new macros?'

![image](https://user-images.githubusercontent.com/68756964/120902407-9d906c00-c616-11eb-886d-e52e53b49033.png)

Thank you for the excelent modules!

**Comment by earlSt1** [comment]
That's strange, I dont remember seeing that when I was testing. Can you send me the foundry version, system, and module version?

**Comment by atleticano-snp** [comment]
Yeah. Just dragging something makes the window pop-up

Foundry 0.8.6
Dnd5e 1.3.3
MacroFolder 1.2.2

**Comment by earlSt1** [comment]
Same as me, but i dont get that in my test world, thats strange. Can you send me your module list?

**Comment by devnagui** [comment]
I'm also having the same issue where any change from anyone(player or gm) causes the macro folder to open for everyone.

My module list is:
about-time--v0.8.5;
ActiveAuras--v0.3.0;
adventure-import-export--v0.6.0;
autoanimations--v0.3.64;
betterrolls5e--v1.5.3;
better-target--v0.1.13;
calendar-weather--v3.1.2;
combat-numbers--v1.1.4;
combatready--v1.1.10;
combat-utility-belt--v1.5.0;
compendium-folders--v2.3.1;
ddb-importer--v2.1.5;
df-chat-enhance--v3.0.2;
dfreds-droppables--v1.2.5;
df-settings-clarity--v3.1.0;
dice-so-nice--v3.4.2;
drag-ruler--v1.7.3;
Dynamic-Effects-SRD--v4.1.13;
dae--v0.8.12;
forien-copy-environment--v2.0.3;
forien-unidentified-items--v0.2.5;
foundry_community_macros--v0.41;
fpsmeter--v1.1.1;
fxmaster--v1.0.10;
healthEstimate--v2.5.8;
JB2A_DnD5e--v0.2.0;
lmrtfy--v1.14;
colorsettings--v2.5.9;
_chatcommands--v1.3.3;
lib-wrapper--v1.6.2.0;
macro-folders--v1.2.2;
midi-qol--v0.8.10;
minimal-ui--v1.0.4;
mobile-improvements--v1.0.2;
multilevel-tokens--v1.5.1;
Next-Up--v0.1.01;
NotYourTurn--v1.1.5;
pings--v1.2.12+0.8.6;
plutonium--v1.29.2;
popout-resizer--v1.3;
potato-or-not--v0.4.3;
Radugen--v0.0.4;
fateroll--v0.4.5;
settings-extender--v1.1.5+0.8.6;
socketlib--v1.0.6;
spellarena--v1.3.0;
0streamutils--v1.1.4;
tidy5e-sheet--v0.5.4;
tidy-ui_game-settings--v0.1.23;
t-is-for-target--v0.4;
vtta-tokenizer--v3.1.4;
tokenmagic--v0.5.1;
touch-vtt--v1.8.0;

**Comment by Koalahund** [comment]
Deleting a macro in the hotbar also causes the macro directory to open.
Foundry 0.8.6
PF1 0.78.8
MacroFolder 1.2.2

**Comment by earlSt1** [comment]
> I'm also having the same issue where any change from anyone(player or gm) causes the macro folder to open for everyone.
> 
> My module list is:
> about-time--v0.8.5;
> ActiveAuras--v0.3.0;
> adventure-import-export--v0.6.0;
> autoanimations--v0.3.64;
> betterrolls5e--v1.5.3;
> better-target--v0.1.13;
> calendar-weather--v3.1.2;
> combat-numbers--v1.1.4;
> combatready--v1.1.10;
> combat-utility-belt--v1.5.0;
> compendium-folders--v2.3.1;
> ddb-importer--v2.1.5;
> df-chat-enhance--v3.0.2;
> dfreds-droppables--v1.2.5;
> df-settings-clarity--v3.1.0;
> dice-so-nice--v3.4.2;
> drag-ruler--v1.7.3;
> Dynamic-Effects-SRD--v4.1.13;
> dae--v0.8.12;
> forien-copy-environment--v2.0.3;
> forien-unidentified-items--v0.2.5;
> foundry_community_macros--v0.41;
> fpsmeter--v1.1.1;
> fxmaster--v1.0.10;
> healthEstimate--v2.5.8;
> JB2A_DnD5e--v0.2.0;
> lmrtfy--v1.14;
> colorsettings--v2.5.9;
> _chatcommands--v1.3.3;
> lib-wrapper--v1.6.2.0;
> macro-folders--v1.2.2;
> midi-qol--v0.8.10;
> minimal-ui--v1.0.4;
> mobile-improvements--v1.0.2;
> multilevel-tokens--v1.5.1;
> Next-Up--v0.1.01;
> NotYourTurn--v1.1.5;
> pings--v1.2.12+0.8.6;
> plutonium--v1.29.2;
> popout-resizer--v1.3;
> potato-or-not--v0.4.3;
> Radugen--v0.0.4;
> fateroll--v0.4.5;
> settings-extender--v1.1.5+0.8.6;
> socketlib--v1.0.6;
> spellarena--v1.3.0;
> 0streamutils--v1.1.4;
> tidy5e-sheet--v0.5.4;
> tidy-ui_game-settings--v0.1.23;
> t-is-for-target--v0.4;
> vtta-tokenizer--v3.1.4;
> tokenmagic--v0.5.1;
> touch-vtt--v1.8.0;

Thanks, i'll look into this when i get the chance (gonna be quite busy this week since i'm moving house)

**Comment by earlSt1** [comment]
So I just fixed another issue with the macro folder directory rendering in the background with no scenes active, and was wondering if it would fix this issue for you. Can you try uninstalling MF and installing using this manifest below?:
https://raw.githubusercontent.com/earlSt1/vtt-macro-folders/08x-update/test/module.json

**Comment by atleticano-snp** [comment]
Sorry for the delay.

Yeah, installed this manifest and the macro folder stopped to pop up. However my knowledge can't help you too much with what happened.
tested in a new world just to try it. Than I tested on my current worlds, believe that's ok now.

**Comment by earlSt1** [comment]
Hmm ok, @devnagui can you try too? If it's not happening anymore for both of you with the new manifest then it may have been what was causing it.

**Comment by yoshikidneo** [comment]
Hello, I'm still having the issue of the macro search bar across the top of my screen, doesn't matter what scene I use it's always there unless I turn the module off.

**Comment by earlSt1** [comment]
> Hello, I'm still having the issue of the macro search bar across the top of my screen, doesn't matter what scene I use it's always there unless I turn the module off.

Hi, are you using the custom manifest link above to check if it fixes it?

**Comment by devnagui** [comment]
Hi @earlSt1, it seems that its fixed. Its not opening anymore using the module.json that you provided.

**Comment by earlSt1** [comment]
Fixed in v1.2.21
